// <auto-generated />
namespace MovieReviews_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ReviewRatingChangedToFloat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReviewRatingChangedToFloat));
        
        string IMigrationMetadata.Id
        {
            get { return "201904072016098_ReviewRatingChangedToFloat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
